config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
  end

  get "/posts/:id/like" => "posts#like_post", :as => :like_post
  get "/posts/:id/dislike" => "posts#dislike_post", :as => :dislike_post
  root 'posts#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  serialize :likearray, Array
  serialize :dislikearray, Array
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:comment))
    @comment.user_id = current_user.id if current_user
    @comment.save

    if @comment.save
      @post.orderscore = @post.likes - (2*(@post.dislikes)) + (4*(@post.comments.count))
      @post.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    if @comment.update(params[:comment].permit(:comment))
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    @post.orderscore = @post.likes - (2*(@post.dislikes)) + (4*(@post.comments.count))
    @post.save
    redirect_to post_path(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :post_finder, only: [:show, :edit, :update, :destroy, :like_post, :dislike_post]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.all.order(orderscore: :desc)
	end

	def show
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)
		@post.likes = 0
		@post.dislikes = 0
		update_orderscore

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

	def like_post
		if !@post.likearray.include?(current_user.id)
			@post.increment!(:likes)
			@post.likearray << current_user.id
		end
		update_orderscore
		@post.save
		redirect_to @post
	end

	def dislike_post
		if !@post.dislikearray.include?(current_user.id)
			@post.increment!(:dislikes)
			@post.dislikearray << current_user.id
		end
		update_orderscore
		@post.save
		redirect_to @post
	end

	def update_orderscore
		@post.orderscore = @post.likes - (2*(@post.dislikes)) + (4*(@post.comments.count))
	end

	private

	def post_finder
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :content)
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.comment.clearfix
  .content
    %p.comment_content= comment.comment
    %p.comment_author= comment.user.email
  .buttons
    = link_to "Edit", edit_post_comment_path(comment.post, comment)
    = link_to "Delete", [comment.post, comment], method: :delete, data: {confirm: "Are you sure you want to delete the reply?"}

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build]) do |f|
  = f.input :comment
  = f.submit

app/views/comments/edit.html.haml
%h1 Edit reply

= simple_form_for([@post, @comment]) do |f|
  = f.input :comment
  = f.submit

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Awesome discussion board
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    %link{ rel: "stylesheet", href: "https://fonts.googleapis.com/css?family=Lato:400,700,300", type: "text/css"}
    %link{ rel: "stylesheet", href: "http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.min.css"}

    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header.main_header.clearfix
      .wrapper
        #logo 
          %p= link_to "Awesome discussion board By Manmeet", root_path
        #buttons
          - if user_signed_in?
            = link_to "New Post", new_post_path
            = link_to "Logout", destroy_user_session_path, method: :delete
          - else
            = link_to "Sign up", new_user_registration_path
            = link_to "Sign In", new_user_session_path
    .wrapper
      %p.notice= notice
      %p.alert= alert
    .wrapper
      .login-details 
        - if user_signed_in?
          Logged in as : 
          = current_user.email
      = yield

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
  #new_post
    %hr/
    .title_post
      %br/
      = f.input :title
      %br/
      = f.input :content
    = f.submit

app/views/posts/edit.html.haml
%h1 Edit Post

= render 'form'

= link_to "Cancel edit", post_path

app/views/posts/index.html.haml
#posts
  - @posts.each do |post|
    .post
      %h2.title= link_to post.title, post
      - if user_signed_in?
        = link_to "Delete Post", post_path(post), method: :delete, data: { confirm: "Are you sure you wanna delete?" }, class: "button", style: "float: right"
        = link_to "Edit Post", edit_post_path(post), class: "button", style: "float: right"
      %p.date
        This post was created
        = time_ago_in_words(post.created_at)
        ago by
        = post.user.email
        .like
          Likes: 
          = post.likes
        .dislike
          Dislikes:
          = post.dislikes
        .comment-in-posts
          Comments:
          = post.comments.count

app/views/posts/like.html.haml
= render "form"

app/views/posts/new.html.haml
%h1 New Post

= render 'form'

app/views/posts/show.html.haml
#post_material
  %h1= @post.title
  %p= @post.content
  = link_to "Dislike post", dislike_post_path(@post), class: "button", style: "float: right"
  = link_to "Like post", like_post_path(@post), class: "button", style: "float: right"
  #comments
    %h3
      = @post.comments.count
      Comments
      %br/
      = @post.likes
      Likes
      %br/
      = @post.dislikes
      Dislikes
    = render @post.comments

    %h3 Reply to thread
    = render "comments/form"

    %br/
    %hr/
    %br/

    = link_to "Edit Post", edit_post_path(@post), class: "button"
    = link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you wanna delete?" }, class: "button"